### ISSUE TITLE
"my media" broken on mobile

### ISSUE THREAD

**Issue by tywentghxst** [Fallenbagel/Hint-of-Colors#2]
Hi! I just found your work and it's one of the best, I definitely love the my media headers, but they seem broken on mobile, could you please look in to fixing it if it's not too much trouble? Thanks for your work!!!
![Screenshot_20220722-025534_Jellyfin.jpg](https://user-images.githubusercontent.com/77469443/180373004-78c5c39b-cd38-4e6d-8029-b1603c8fd3dd.jpg)

**Comment by fallenbagel** [comment]
Hi. As mentioned in my readme, in hint of colors, you will have to change my media to my media (small) for it to work
![image](https://user-images.githubusercontent.com/98979876/180448936-3375ea0b-c399-42ec-bdfb-e66464b05717.png)

**Comment by tywentghxst** [comment]
> Hi. As mentioned in my readme, in hint of colors, you will have to change my media to my media (small) for it to work
> ![image](https://user-images.githubusercontent.com/98979876/180448936-3375ea0b-c399-42ec-bdfb-e66464b05717.png)

Ahhhhh my apologies, I don't know how I missed that when I was looking🤦‍♂️🤦‍♂️🤦‍♂️

I did however find a way to make it work without using small media using some of your code to look like this
![Screenshot_20220722-114639_Gallery.jpg](https://user-images.githubusercontent.com/77469443/180464541-d96cbc4b-9a26-4b06-a614-975e871f2393.jpg)

But I'm definitely gonna retry yours tonight because it looked great! Thanks for the help

**Comment by fallenbagel** [comment]
ooo how did you set it up. Maybe i can put that as an option for peeps

**Comment by tywentghxst** [comment]
This is what made it work like that for me on mobile, I think the biggest thing that annoys me for it is it's not fully centered tho on mobile lol, can't seem to figure that out, seems to change the center position if you try to up the VW variable on the last line here where I have it at 28vw


@media (max-width: 62.5em) {
.section0 .cardText.cardTextCentered.cardText-first {
height:2.5em
}
}
.section0 button.itemAction.textActionButton {
background:rgba(0,0,0,0);
border-radius:var(--rounding);
height:3.5em
}

.section0 .overflowBackdropCard,.section0 .overflowSmallBackdropCard {
max-width:90vw
}

.section0 .emby-scroller {
margin-right:0
}

@media (max-width: 1px) and (orientation: landscape) {
.section0 {
display:none
}
}

.section0 .sectionTitle {
padding-top:60px!important
}

@media (max-width: 1px) {
.section0 {
display:none
}
}

.section0 .sectionTitle {
display:none
}


.section0 .itemsContainer {
    align-items: center;
    justify-content: center;
    margin-top: 0px;
}

.section0 .overflowBackdropCard,
.section0 .overflowSmallBackdropCard {
    max-width: 28vw
}

**Comment by fallenbagel** [comment]
> This is what made it work like that for me on mobile, I think the biggest thing that annoys me for it is it's not fully centered tho on mobile lol, can't seem to figure that out,

have you tried `self-align: center`?

**Comment by tywentghxst** [comment]
Yes, depending on the size though it becomes off center, I've just went with removing the center alignment and that seemed to have fixed it,, is there any chance you know a way to make a self align center Command only work on desktop and not mobile?

**Comment by fallenbagel** [comment]
Anything written with 
`.layout-mobile` infront would only affect mobile so you can use that to do that

**Comment by tywentghxst** [comment]
Thanks!! I'll give it a try
